### ISSUE TITLE
Please read

### ISSUE THREAD

**Issue by VXT108** [Panthere/SnipeBot#9]
First off I would like to thank you (Panthere) for developing everything that you do. It helps many people out and I am grateful. I have however noticed that you do not have an issues page on you GoBot so I came here (sorry). Anyway I came here to share the new API with you [https://github.com/keyphact/pgoapi](url) (just in case you did not see it yet). I am not an experienced programmer and I am not even sure how long it will take to fix GoBot or if you even will fix it. I know that it is your most starred project though and that many people would appreciate if you would update and fix it. I for one, like your Pokemon Go bot the best, and would be disappointed if you deiced to end it. Again sorry for adding this on one of your other project's issues page, and thank you for everything you put up for us to use.

**Comment by Panthere** [comment]
I've seen the api, the problem is, it's python, waiting for ferox to officially update his api...
I feel that my bot is not the best out there, and I have very little time to dedicate towards it.
I am happy to update it and fix it, but there is a lot that needs to be improved.

**Comment by VXT108** [comment]
Ok. Though your bot may not be the best it has a lot of potential. Thank you for replying.
